set_property SRC_FILE_INFO {cfile:D:/PROJECTS/LED/LED.srcs/constrs_1/new/LED_switch_const.xdc rfile:../../../LED.srcs/constrs_1/new/LED_switch_const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports switch]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports led]
